### ISSUE TITLE
Sequential Download and Video Streaming on ADC 

### ISSUE THREAD

**Issue by ravaan** [ehmry/go-adc#1]
Is there a sequential download option available for ADC protocol?

I also wanted to ask whether there is a way to directly stream a TTH/Magnet of a file from an ADC Hub, wasn't able to find any implementation online as of yet.

I was working on making a streaming service on top of the DC network we have on our campus.

**Comment by ehmry** [comment]
IDK, I wrote this years ago and now I don't know how to write Go anymore.

**Comment by ravaan** [comment]
Haha! Nevermind I got some leads on another project called dctoolkit. BTW, how do you unlearn a language? 🤣

**Comment by ehmry** [comment]
I had to stop using Go because of the lack of metaprogramming, and I don't know what the fashionable Go idiom is anymore. Its seems I should also know what the perceived implementation of sequences is so that I can write code that looks fast, which defeats the purpose of Go. Also, languages that rely on "package management" suck.
